kind: pipeline
name: Unit Tests
platform:
  os: linux
  arch: amd64

clone:
  depth: 1

trigger:
  event:
    - push

environment:
  CGO_ENABLED: 0

steps:
  - name: run linter
    image: golangci/golangci-lint:v1.62.2-alpine
    commands:
      - golangci-lint run --timeout 180s

  - name: scan the files
    image: aquasec/trivy:0.58.0
    commands:
      - trivy fs --exit-code 1 --scanners vuln,config ./
      - trivy config --exit-code 1 ./

  - name: go test
    image: golang:1.23-alpine
    commands:
      - apk add --no-cache git
      - go vet ./...
      - go test -v $(go list ./... | grep -v /internal/tests/run$)

---
kind: pipeline
name: Wasm/Pack Scenarios
platform:
  os: linux
  arch: amd64

clone:
  depth: 1

trigger:
  branch:
    - v2/si
  event:
    - push
    - tag
    - pull_request

environment:
  CGO_ENABLED: 0
  KNOX_DRIVER: mem
  KNOX_ENGINE: pack
  MINIO_BUCKET: scenarios
  MINIO_URL: h3.bwd.cx

steps:
  - name: go test
    image: golang:1.23-alpine
    commands:
      - apk add --no-cache git
      - go test $(go list ./... | grep -v /internal/tests/run$)
      - go test -v ./internal/tests/run -timeout 1h -system wasm

---
kind: pipeline
name: Native/Pack Scenarios
platform:
  os: linux
  arch: amd64

clone:
  depth: 1

trigger:
  branch:
    - v2/si
  event:
    - push
    - tag
    - pull_request

environment:
  CGO_ENABLED: 0
  KNOX_DRIVER: mem
  KNOX_ENGINE: pack
  MINIO_BUCKET: scenarios
  MINIO_URL: h3.bwd.cx

steps:
  - name: go test
    image: golang:1.23-alpine
    commands:
      - apk add --no-cache git
      - go test $(go list ./... | grep -v /internal/tests/run$)
      - go test -v ./internal/tests/run -timeout 1h -system native

---
kind: pipeline
name: Native/LSM Scenarios
platform:
  os: linux
  arch: amd64

clone:
  depth: 1

trigger:
  branch:
    - v2/si
  event:
    - push
    - tag
    - pull_request

environment:
  CGO_ENABLED: 0
  KNOX_DRIVER: mem
  KNOX_ENGINE: pack
  MINIO_BUCKET: scenarios
  MINIO_URL: h3.bwd.cx

steps:
  - name: go test
    image: golang:1.23-alpine
    commands:
      - apk add --no-cache git
      - go test $(go list ./... | grep -v /internal/tests/run$)
      - go test -v ./internal/tests/run -timeout 1h -system native
