kind: pipeline
name: Unit Tests
platform:
  os: linux
  arch: amd64

clone:
  depth: 1

trigger:
  event:
    - push
    - pull_request

environment:
  CGO_ENABLED: 0
  GOPATH: /go

image_pull_secrets:
  - DOCKER_LOGIN

volumes:
  - name: cache
    host:
      path: /var/cache/build

steps:
  - name: lint
    image: golangci/golangci-lint:v2.2.1-alpine
    volumes:
      - name: cache
        path: /go
    commands:
      - golangci-lint run --timeout 180s

  - name: scan
    image: aquasec/trivy:0.64.1
    volumes:
      - name: cache
        path: /go
    commands:
      - trivy fs --exit-code 1 --scanners vuln,misconfig,secret --skip-files "./scripts/docker/*" ./
      - trivy config --exit-code 1 --skip-files "./scripts/docker/*" ./

  - name: vet
    image: golang:1.25-alpine
    volumes:
      - name: cache
        path: /go
    commands:
      - go vet $(go list ./... | grep -v cmp/avx | grep -v wasm/vfs | grep -v filter/llb | grep -v filter/bloom | grep -v hash/xxhash | grep -v s8b/avx2 | grep -v hashprobe )

  - name: unit
    image: golang:1.25-alpine
    volumes:
      - name: cache
        path: /go
    commands:
      - apk add --no-cache git
      - go test -v $(go list ./... | grep -v /internal/tests) -tags with_assert

  - name: scenario wasm/mem/pack
    image: hub.bwd.cx/go-dst:1.24.5-alpine
    volumes:
      - name: cache
        path: /go
    environment:
      KNOX_DRIVER: mem
      KNOX_ENGINE: pack
      MINIO_BUCKET: scenarios
      MINIO_URL: hd1.bwd.cx:9001
      MINIO_USER:
        from_secret: MINIO_USER
      MINIO_SECRET:
        from_secret: MINIO_SECRET
    commands:
      - apk add --no-cache git
      - go run -buildvcs=true ./internal/tests/run -count 100 -arch wasm -timeout 10m
    depends_on:
      - lint
      - scan
      - vet
      - unit

  - name: scenario native/bolt/pack
    image: hub.bwd.cx/go-dst:1.24.5-alpine
    volumes:
      - name: cache
        path: /go
    environment:
      KNOX_DRIVER: bolt
      KNOX_ENGINE: pack
      MINIO_BUCKET: scenarios
      MINIO_URL: hd1.bwd.cx:9001
      MINIO_USER:
        from_secret: MINIO_USER
      MINIO_SECRET:
        from_secret: MINIO_SECRET
    commands:
      - apk add --no-cache git
      - go run -buildvcs=true ./internal/tests/run -count 100 -arch native -timeout 10m
    depends_on:
      - lint
      - scan
      - vet
      - unit
