version: "2"
linters:
  enable:
    - bodyclose
    - copyloopvar
    - durationcheck
    - gocritic
    - gomoddirectives
    - prealloc
    - reassign
    - unconvert
    - unparam
  disable:
    - errcheck
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - docs/
      - scripts/
      - examples/
      - playground/
  settings:
    gocritic:
      disabled-checks:
        - dupSubExpr
formatters:
  enable:
    - gofmt
  exclusions:
    generated: lax
    paths:
      - docs/
      - scripts/
      - examples/
      - playground/
