linters:
  enable:
    - bodyclose
    - durationcheck
    - copyloopvar 
    - gomoddirectives
    - prealloc
    - reassign
    - gocritic
    - gofmt
    - govet
    - prealloc
    - unconvert
    - unparam
    - gosimple
    - unused
  disable:
   - errcheck
