//go:build amd64

// Code generated by command: go run asm.go -out asm_x86.s -stubs asm_x86.go. DO NOT EDIT.

package xroar

import (
	cpu "github.com/klauspost/cpuid/v2"
)

// bitmapOrAvx2 performs an Or operation between data []uint16 and other []uint16.
// Returns data with values and cardinality.
//
//go:noescape
func bitmapOrAvx2(data []uint16, other []uint16) int

// bitmapAndAvx2 performs an And operation between data []uint16 and other []uint16.
// Returns data with values and cardinality.
//
//go:noescape
func bitmapAndAvx2(data []uint16, other []uint16, buf []uint16) int

// bitmapAndNotAvx2 performs an AndNot operation between data []uint16 and other []uint16.
// Returns data with values and cardinality.
//
//go:noescape
func bitmapAndNotAvx2(data []uint16, other []uint16, buf []uint16) int

func init() {
	// Check for CPU SIMD
	if cpu.CPU.Supports(cpu.AVX, cpu.AVX2, cpu.POPCNT) {
		bitmapOr = bitmapOrAvx2
		bitmapAnd = bitmapAndAvx2
		bitmapAndNot = bitmapAndNotAvx2
	}
}
